name: C/C++ CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  linux:

    strategy:
      fail-fast: false
      matrix:
        graphics: [vulkan, vulkan gles]

    name: linux build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: install packages
        run: |
          sudo apt-get update -m && sudo apt-get install xorg-dev libvulkan-dev
        shell: bash
      - name: Run cmake
        uses: lukka/run-cmake@v2
        with:
          buildDirectory: '${{runner.workspace}}/build'
      - name: Dump vulkaninfo
        run: 'vulkaninfo'
      - name: Run
        run: 'cd ${{runner.workspace}}/build && ./main'
