name: master build-gl

on:
  push:
    branches: [ master ]

env:
  CC: gcc-9
  CXX: gcc-9

jobs:
  linux:

    name: linux build
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: install packages
        run: |
          sudo apt-get update -m && sudo apt-get install xorg-dev && sudo apt-get install libgl-dev
        shell: bash
      - name: cmake build
        uses: lukka/run-cmake@v2
        with:
          buildDirectory: '${{runner.workspace}}/build'
